// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAioD273y3Ife-0r7mfkbpKH0uVeVGR4i4',
    appId: '1:789491833971:web:abcef247b62d5ae38b1e06',
    messagingSenderId: '789491833971',
    projectId: 'csmyapp-f15fb',
    authDomain: 'csmyapp-f15fb.firebaseapp.com',
    databaseURL: 'https://csmyapp-f15fb-default-rtdb.firebaseio.com',
    storageBucket: 'csmyapp-f15fb.appspot.com',
    measurementId: 'G-TPHY5YKPZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKLmCGxd7EulLh1Shbg5wDWKMf4rR498w',
    appId: '1:789491833971:android:c5b0dae25da3dc908b1e06',
    messagingSenderId: '789491833971',
    projectId: 'csmyapp-f15fb',
    databaseURL: 'https://csmyapp-f15fb-default-rtdb.firebaseio.com',
    storageBucket: 'csmyapp-f15fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaaXTHR9Bp_IBMzZCs_CMe0TEsfXP6eBk',
    appId: '1:789491833971:ios:f08cde9b916d928d8b1e06',
    messagingSenderId: '789491833971',
    projectId: 'csmyapp-f15fb',
    databaseURL: 'https://csmyapp-f15fb-default-rtdb.firebaseio.com',
    storageBucket: 'csmyapp-f15fb.appspot.com',
    iosClientId: '789491833971-r6is1dppm2c19409pd93drgq8ojbukmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaaXTHR9Bp_IBMzZCs_CMe0TEsfXP6eBk',
    appId: '1:789491833971:ios:f08cde9b916d928d8b1e06',
    messagingSenderId: '789491833971',
    projectId: 'csmyapp-f15fb',
    databaseURL: 'https://csmyapp-f15fb-default-rtdb.firebaseio.com',
    storageBucket: 'csmyapp-f15fb.appspot.com',
    iosClientId: '789491833971-r6is1dppm2c19409pd93drgq8ojbukmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );
}
